name: cd

on:
  push
  # branches: master

jobs:
  cd:
    name: cd
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.20.4
          cache-dependency-path: app/go.sum
      - run: go build main.go
      - run: ls -la
      - run: tar -xvf ./main.exe vpc_overrider.tar.gz
      - run: ls -la
