name: tag

on:
  push:
    branches:
      - master
jobs:
  Patch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: version
        id: AutoTagger
        uses: anothrNick/github-tag-action@1.65.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
